### ISSUE TITLE
Can't install flutter_cache_manager

### ISSUE THREAD

**Issue by Edmand** [renefloor/flutter_cache_manager#11]
I added the flutter_cache_manager: "^0.1.0" to my project pubspec.yaml and get an error below when I ran the flutter packages get command. 

Running "flutter packages get" in MyApp...
Package flutter_cache_manager has no versions that match >=0.1.0 <0.2.0 derived from:
- myapp depends on version ^0.1.0
pub get failed (1)
exit code 1

**Comment by renefloor** [comment]
Are you using Dart 2.0?
Can you post the output of Flutter doctor?

**Comment by EdmandKansys** [comment]
I'm using Dart 1.0 with Visual Studio Code. Below is my flutter doctor output.

d:\Projects\FlutterProjects\MyApp>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.16299.371], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] VS Code, 32-bit edition (version 1.21.1)
[√] Connected devices (1 available)

• No issues found!

**Comment by EdmandKansys** [comment]
I have upgraded Flutter and it is still giving me the same error. Below is the Flutter Doctor output.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 10.0.16299.371], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] VS Code, 32-bit edition (version 1.21.1)
[√] Connected devices (1 available)

• No issues found!

**Comment by RisingSunStudios** [comment]
I've had the same issue with no luck resolving it. It was working up until half hour ago, up until I added json_annotation to my pubspec.yaml and now I get 

``Package flutter_cache_manager has no versions that match >=0.1.1 <0.2.0 derived from:
- cached_network_image 0.4.1 depends on version ^0.1.1
pub get failed (1)
exit code 1

my pubspec file looks like this:

``dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  async_loader: ^0.1.1
  http: ^0.11.3+16
  path_provider: ^0.4.0
  cached_network_image: ^0.4.1
  uuid: 1.0.0
  json_annotation: ^0.2.3

dev_dependencies:
  build_runner: ^0.8.0
  json_serializable: ^0.5.0
  flutter_test:
    sdk: flutter

**Comment by pyros2097** [comment]
@RisingSunStudios You have uuid: 1.0.0
Then this could be the error
https://github.com/renefloor/flutter_cache_manager/issues/26

**Comment by iEdric** [comment]
Because flutter_cache_manager 0.1.1 depends on uuid ^0.5.3 and no versions of flutter_cache_manager match >0.1.1 <0.2.0, flutter_cache_manager ^0.1.1 requires uuid ^0.5.3.
And because cached_network_image >=0.4.1 depends on flutter_cache_manager ^0.1.1, cached_network_image >=0.4.1 requires uuid ^0.5.3.
So, because flutter_app02 depends on both cached_network_image ^0.4.1 and uuid ^1.0.0, version solving failed.
pub get failed (1)

**Comment by Cretezy** [comment]
Use:

```
dependencies:
  flutter_cache_manager:
    git: https://github.com/Cretezy/flutter_cache_manager.git
```

**Comment by aj3sh** [comment]
@Cretezy And for cached_image_network ??? It depends on flutter_cache_manager ^0.1.1

**Comment by Cretezy** [comment]
@aj3sh 

```
dependencies:
  cached_network_image:
    git: https://github.com/Cretezy/flutter_cached_network_image.git
```
