### ISSUE TITLE
Is cache path ".../cachecache/..." a bug?

### ISSUE THREAD

**Issue by coolzilj** [renefloor/flutter_cache_manager#15]
I'm playing with the[ flutter_cached_network_image]( https://github.com/renefloor/flutter_cached_network_image ) , trying to figure out how and where images are cached.

With the help of `CacheManager.getFile`, I noticed that the path of cache images
`/data/user/0/com.example.helloworld/cachecache/4fd9d460-4800-11e8-e6b9-3f018955612d.jpeg`
 is different with the `getTemporaryDirectory` by `path_provider` which is something like this
`/data/user/0/com.example.helloworld/cache/hello_worldLNOPCM/hello_world/build/flutter_assets/AssetManifest.json`

So, is this a bug?

**Comment by renefloor** [comment]
I'll have to look into this for Android and iOS, but it looks like it indeed it looks like this is indeed a real problem. I don't know why I didn't see this before. Maybe `getTemporaryDirectory` changed or something like that.

**Comment by sgon00** [comment]
@coolzilj I am wondering why you close this bug, since the cache directory is still `cachecache/` now. If it shouldn't be this directory, this bug should still remain open.

**Comment by renefloor** [comment]
@sgon00 I agree

**Comment by renefloor** [comment]
Fixed in `0.3.0-alpha.2`
