### ISSUE TITLE
A way to evict urls from the cache

### ISSUE THREAD

**Issue by Panthro** [renefloor/flutter_cache_manager#20]
Hi

I'm using cache manager for images but for some api calls as well, I load some json that change once a week.

The thing is, there is no way to evict a url from cache manually when I know the data has changed.

If we could have several cache managers, like mentioned in #5 that would do, because I can setup a distinct eviction strategy for these files.

**Comment by Panthro** [comment]
Btw currently what I'm doing to avoid the cache manager from always caching the api data I'm setting a cachebuster param in the url that is fixed to the week number of the year

**Comment by kmorkos** [comment]
This would be great for me as well, I have some files that can be updated and I need to be able to clear them from the cache when that happens.

**Comment by fhuonder** [comment]
We also need this functionality.
A pull request is already available. Please pull it in and make a new release.

**Comment by renefloor** [comment]
I added the functionality to remove specific urls from the cache in `0.3.0-alpha.2`.
