### ISSUE TITLE
Need public methods to clear cache or clear selected files from it

### ISSUE THREAD

**Issue by gregko** [renefloor/flutter_cache_manager#25]
Example: I was trying to download CachedNetworkImage, that required authentication. Forgot to give correct authentication headers (or gave a wrong one). Now cache manager saves as my image an http response - a web page asking to log-in. Code crashes trying to create a JPEG image from that HTML code... There is no official way to remove that bad "image" from the cache until it expires.

**Comment by renefloor** [comment]
@gregko in version `0.3.0-alpha.2` I added a method to remove specific urls from the cache.

**Comment by gregko** [comment]
Thank you, @renefloor, will use it in the next release of my product. I appreciate very much your contributions to Flutter project!
