### ISSUE TITLE
[URGENT] UUID Library Needs Updating!

### ISSUE THREAD

**Issue by codeZee** [renefloor/flutter_cache_manager#36]
This is happening with many developers using the caching library. We hope its a quick update (with little to no breakage) on your end. The new versions of uuid have this PI variable taken off.

The error:
compiler message: file:///Users/user/.pub-cache/hosted/pub.dartlang.org/uuid-0.5.3/lib/uuid.dart:20:24: Error: Getter not found: 'PI'.
compiler message:   static final TAU = 2*PI;
compiler message:    

Related:
https://github.com/renefloor/flutter_cached_network_image/issues/62

**Comment by llearn** [comment]
+1 @renefloor

**Comment by thenexus00** [comment]
We have come up with this as well - Because flutter_cache_manager 0.1.1 depends on uuid >=0.0.7 <1.0.3 which requires SDK version <2.0.0, flutter_cache_manager 0.1.1 is forbidden.

Needs to be updated ASAP, nearly a week now with no change.

**Comment by Cretezy** [comment]
Use:

```
dependencies:
  flutter_cache_manager:
    git: https://github.com/Cretezy/flutter_cache_manager.git
```
