### ISSUE TITLE
How to manually add item to Cache Manager

### ISSUE THREAD

**Issue by FastNinja** [renefloor/flutter_cache_manager#4]
Hi Rene,
I am about to start using Cache Manager to cache documents.
Imagine a scenario where user selects a local document which is then uploaded to the Cloud.

All other users will use cache manager to download that document and see.

However the user who just uploaded document - should not need to download it again.

For example - chat app. I pick a local PDF document and send a message.
The document is uploaded. At this stage I want to give Cache manager document with certain path - so it won't download it .
Otherwise there is a massive delay - (as document needs to be downloaded) or very complicated logic on a client (we need to track whether the document was local and store local copy (as on iOS documents are accesible only for short period of time after picking))

**Comment by renefloor** [comment]
That is indeed a nice feature. It has currently a very low priority for me, but I am willing to review a pull request.

**Comment by illia-romanenko** [comment]
it would be nice to have this feature merged & available

**Comment by renefloor** [comment]
Added this functionality in `0.3.0-alpha.2`.
