### ISSUE TITLE
A way to handle Digest authentication is needed

### ISSUE THREAD

**Issue by gregko** [renefloor/flutter_cache_manager#45]
The Basic authentication scheme can be handled with HTTP headers, so no problem here. However with Digest (and possibly other) auth schemes, the server responds with status 401 "unauthorized" and sends back 'www-authenticate' header with the data necessary to generate correct 'Authorization' header and re-post. Currently handling this within CacheManager class seems impossible. If someone knows how this could be handled, please correct me and explain how.

**Comment by lifenautjoe** [comment]
The pull request #53 fixes this. Just waiting for merge.

**Comment by renefloor** [comment]
Added in `0.3.0-alpha.2`
