### ISSUE TITLE
Packages get and upgrade failed

### ISSUE THREAD

**Issue by pojoba02** [renefloor/flutter_cache_manager#48]
Please you need to update and upgrade http in pubspec.yaml, from 0.11.3+4 to 0.12.0.Running "flutter 

packages upgrade" in app.....
Because every version of flutter_test from sdk depends on http 0.12.0 and flutter_cache_manager >=0.1.0-rc.1 depends on http ^0.11.3+14, flutter_test from sdk is incompatible with flutter_cache_manager >=0.1.0-rc.1.
And because cached_network_image >=0.4.2 depends on flutter_cache_manager ^0.1.2, flutter_test from sdk is incompatible with cached_network_image >=0.4.2.
So, because app depends on both cached_network_image ^0.4.2 and flutter_test any from sdk, version solving failed.

**Comment by noordawod** [comment]
For now, you can fix by adding the following your `pubspec.yaml` file:

```
dependency_overrides:
  http: ^0.12.0
```
