### ISSUE TITLE
Downloading Firebase cloud storage files

### ISSUE THREAD

**Issue by aloisdeniel** [renefloor/flutter_cache_manager#61]
Hi,

I'm looking to a way of caching files stored on Firebase cloud storage. Today, the API doesn't seems to allow to tweak the way files are downloaded.

I would like to intercept download request and use my own logic instead of using http download.

We could create an abstraction that would allow to customize the download process :

```dart
abstract class DownloadRequest {
  Future<Uint8List> download();
}

class HttpDownloadRequest extends DownloadRequest {
  final String url;
  final Map<String, String> headers;
  HttpDownloadRequest({@required this.url, this.headers});

  Future<Uint8List> download() async {
    // current logic in Future<CacheObject> _downloadFile(
  }
}

class FirebaseStorageDownloadRequest extends DownloadRequest {
  final StorageReference reference;
  FirebaseStorageDownloadRequest({@required this.reference});

  Future<Uint8List> download() async {
    // use storage api
  }
}
```

With this we could use a `DownloadRequest` instead of a simple url when getting a file.

```dart
Future<File> getFile(String url, {Map<String, String> headers}) async {
  final downloadRequest = HttpDownloadRequest(url: url, headers: headers);
  return requestFile(downloadRequest);
}

Future<File> requestFile(DownloadRequest request) async {
  // ...
}
```

**Comment by aloisdeniel** [comment]
As a temporary solution you can use `getDownloadURL()` to get an url, but that's not acceptable from a security standpoint since provided URLs are public.

**Comment by aloisdeniel** [comment]
Great! Thanks.

And will this functionality be available from `flutter_cached_network_image` as well (for displaying images from Firebase storage) ?

**Comment by renefloor** [comment]
@aloisdeniel yes, if you use https://pub.dartlang.org/packages/cached_network_image/versions/0.6.0-alpha.2 you can already extend the cache manager that is used.

**Comment by The-Redhat** [comment]
@renefloor when do you plan to push the alpha to stable ? I really need the new version, but cannot use alpha because of version conflicts.

**Comment by renefloor** [comment]
@The-Redhat which version conflicts do you have?

**Comment by The-Redhat** [comment]
With flutter_html_view. The library depends on cached_network_image.

**Comment by aloisdeniel** [comment]
@renefloor I will try that very soon and keep you informed! Thanks

**Comment by renefloor** [comment]
Just moved this to beta. Will nog focus on updating and improving the cached_network_image.
