### ISSUE TITLE
if download fail,retry down?

### ISSUE THREAD

**Issue by mrstluo** [renefloor/flutter_cache_manager#71]
In WebHelper, maybe  _memCache have problem ?

**Comment by PeterZainzinger** [comment]
I experienced the issue myself but it seems to by fixed [this commit](https://github.com/renefloor/flutter_cache_manager/commit/f00b6e079a582f6479b193de0daa0d91bd4f2cdf) so we just have to wait for the next release

**Comment by renefloor** [comment]
Should be fixed in 0.3.2
