### ISSUE TITLE
Missing await

### ISSUE THREAD

**Issue by rmarau** [renefloor/flutter_cache_manager#72]
Hi

In cache_manager.dart > BaseCacheManager#getSingleFile 

you  might be missing a dart "await" when downloading after a non-valid cache hit.

**Comment by renefloor** [comment]
No that is on purpose to improve the speed of showing the image. It directly shows the old image and then updates the file in the background. That is mainly beneficial when the validity is not correctly implemented or the file is old, but still valid. It is also said in the docs (although this could be clearer):

"When a file is cached it is return directly, when it is too old the file is downloaded in the background."

So it is returned directly, but updated for the next time.

**Comment by rmarau** [comment]
Thanks

I missed that angle. So the updated file will come up only in the next call (if download completed).
