### ISSUE TITLE
Sqlite replaces SP 

### ISSUE THREAD

**Issue by suojingchao** [renefloor/flutter_cache_manager#8]
I think you can consider to use Sqlite replaces SP. Because of the type of the data that persists is JSON.

**Comment by renefloor** [comment]
Yes true, I indeed think SQLite is better suited for this, but I didn't feel comfortable using it yet when I started this project as sqflite didn't look really stable yet. When I rewrite some of this library I will definitely move to SQLite.

**Comment by jeprojects** [comment]
Any update when you would be likely moving to SQLite?

**Comment by renefloor** [comment]
I am currently working on a redesign of the library to make it more flexible and more easily add new features. I will probably directly move to SQLite while doing that. You can follow the progress on [this branch](/renefloor/flutter_cache_manager/tree/feature/seperation-of-functions)

**Comment by jeprojects** [comment]
Checking out the branch, I like the direction you are going. Thanks for hard work.

Are you going to preload the cache from sqlite first or do single queries each time a new getFile is requested?

**Comment by renefloor** [comment]
I'm not sure yet. I don't like the way I cache everything in memory as the library does now, but I don't really know how quick sqlite on Flutter currently is. Perhaps I do a combination, query from sqlite when a file is requested and keep that result in memory.

I'm also thinking about how to do the cleaning of the cache. Cleaning should be easier when you can query on sqlite. Currently I check if I have to clean after getting a file, but that is not really efficient when the file manager is still retrieving other files. Perhaps I keep track of how many files are being retrieved and after the last file is served I will clean the cache or something like that. Input is very much appreciated.

**Comment by renefloor** [comment]
Fixed in `0.3.0-alpha.2`
