### ISSUE TITLE
[Bug] relativePath will `null`.

### ISSUE THREAD

**Issue by Guang1234567** [renefloor/flutter_cache_manager#80]
Hello dev:

Sometimes `relativePath` field will be null in `data/data/com.abc.xyz/databases/libCachedImageData.db`. 

It will  make the `data/data/com.abc.xyz/libCachedImageData` create as `File` (not folder), so flutter app crash at `putFile(cachedObj)` in next cache operation .

But i cannot reappear it.

![image](https://user-images.githubusercontent.com/8240718/56269142-9ac81980-6125-11e9-9910-f580cf50cc9c.png)

so i track the code maybe this line cause it:

https://github.com/renefloor/flutter_cache_manager/blob/7e7e47a2331fd41894c89c135751df4bfbb2a09b/lib/src/cache_store.dart#L62

**Comment by PerLycke** [comment]
@friebetill Is this the exception thrown, which you fixed in your PR? https://github.com/renefloor/flutter_cache_manager/issues/103

**Comment by friebetill** [comment]
Yeah, I think that's the one.

**Comment by yrom** [comment]
I think the NULL means the cached file maybe been deleted
