### ISSUE TITLE
How to get cache size in folder cache

### ISSUE THREAD

**Issue by Yeikel200** [renefloor/flutter_cache_manager#83]
I want to know the size of the cache folder. There is some method that debits the size of that folder.

**Comment by lijy91** [comment]
My solution:

```dart
String cacheSize = '0 MB';
final directory = Directory(await DefaultCacheManager().getFilePath());
if (directory.existsSync()) {
  FileStat fileStat = directory.statSync();
  cacheSize = '${(fileStat.size / 1024.0).toStringAsFixed(2)} MB';
}
print(cacheSize);
```

**Comment by Yeikel200** [comment]
@lijy91 gracias !!

**Comment by DSPerson** [comment]
`getFilePath ` this function not found

**Comment by Yeikel200** [comment]
@DSPerson This method was withdrawn by decision of the author, for more information you can see it here !!
https://github.com/Baseflow/flutter_cache_manager/issues/239#issuecomment-719475429
