### ISSUE TITLE
please upgrade the  path_provider version.

### ISSUE THREAD

**Issue by badboy-tian** [renefloor/flutter_cache_manager#87]
Thank you  very much

**Comment by alexjuniodev** [comment]
Is there any news on this?

**Comment by sawankumarbundelkhandi** [comment]
Override dependency until the pull request [#85](https://github.com/renefloor/flutter_cache_manager/pull/85) is merged.

https://dart.dev/tools/pub/dependencies#dependency-overrides

dependency_overrides:
  path_provider: ^1.1.0

**Comment by renefloor** [comment]
Fixed
