### ISSUE TITLE
recommended to upgrade path_provider: "^0.5.0+1" to the latest "^1.1.0"

### ISSUE THREAD

**Issue by ChessLuo** [renefloor/flutter_cache_manager#88]
It is recommended to upgrade path_provider: "^0.5.0+1" to the latest "^1.1.0" to resolve conflicts.

**Comment by alexjuniodev** [comment]
Is there any news on this?

**Comment by badboy-tian** [comment]
+1

**Comment by searchy2** [comment]
> Because cached_network_image >=0.7.0 depends on flutter_cache_manager ^0.3.2 which depends on path_provider ^0.5.0+1, cached_network_image >=0.7.0 requires path_provider ^0.5.0+1.

**Comment by hu1095878620** [comment]
+1

**Comment by alanppxmw** [comment]
+1

**Comment by rhymelph** [comment]
+1

**Comment by sawankumarbundelkhandi** [comment]
Override dependency until the pull request #85 is merged.

https://dart.dev/tools/pub/dependencies#dependency-overrides

dependency_overrides:
  path_provider: ^1.1.0

**Comment by zingwin** [comment]
Because audioplayers >=0.12.0 depends on path_provider ^1.1.0 and flutter_cache_manager >=0.3.0 depends on path_provider ^0.5.0+1, audioplayers >=0.12.0 is incompatible with flutter_cache_manager >=0.3.0.

**Comment by zingwin** [comment]
+1

**Comment by navid-ahrary** [comment]
+1

**Comment by HPressure** [comment]
> 
> 
> Override dependency until the pull request #85 is merged.
> 
> https://dart.dev/tools/pub/dependencies#dependency-overrides
> 
> dependency_overrides:
> path_provider: ^1.1.0
How do you properly override it? I'm getting this error when I'm putting these 2 lines in dependecies
Because flutter_app depends on dependency_overrides from unknown source "path_provider", version solving failed.
pub upgrade failed (1)

**Comment by ThinkDigitalSoftware** [comment]
> Because flutter_cache_manager 0.3.2 depends on path_provider ^0.5.0+1 and no versions of flutter_cache_manager match >0.3.2 <0.4.0, flutter_cache_manager ^0.3.2 requires path_provider ^0.5.0+1.
> Thus, cached_network_image ^0.8.0 requires path_provider ^0.5.0+1.
> 
> pub get failed (1)
> exit code 1

Yeah, I get exactly this as well

**Comment by ThinkDigitalSoftware** [comment]
> Override dependency until the pull request #85 is merged.
> 
> https://dart.dev/tools/pub/dependencies#dependency-overrides
> 
> dependency_overrides:
> path_provider: ^1.1.0

WOW! I didn't know about this!!!! Thanks!

**Comment by navid-ahrary** [comment]
> > Because flutter_cache_manager 0.3.2 depends on path_provider ^0.5.0+1 and no versions of flutter_cache_manager match >0.3.2 <0.4.0, flutter_cache_manager ^0.3.2 requires path_provider ^0.5.0+1.
> > Thus, cached_network_image ^0.8.0 requires path_provider ^0.5.0+1.
> > pub get failed (1)
> > exit code 1
> 
> Yeah, I get exactly this as well

use path_provider ^0.5.0+1 to solve issue temporally

**Comment by ThinkDigitalSoftware** [comment]
This is what I get with that path provider version

**Comment by ThinkDigitalSoftware** [comment]
This error is what I get with that path provider version. The dependency override worked fine

`path_provider: ^0.5.0+1`

**Comment by adrianvintu** [comment]
Please fix this.

**Comment by renefloor** [comment]
Fixed
