### ISSUE TITLE
exception 拦截不下来

### ISSUE THREAD

**Issue by lifetin** [renefloor/flutter_cache_manager#94]
![55](https://user-images.githubusercontent.com/10474968/60036599-2770f400-96e2-11e9-8f7c-7a45279c1da2.png)
![44](https://user-images.githubusercontent.com/10474968/60036600-2770f400-96e2-11e9-9094-74a08684c35a.png)

出现异常。
HandshakeException (HandshakeException: Connection terminated during handshake)

**Comment by lifetin** [comment]
![66](https://user-images.githubusercontent.com/10474968/60036700-67d07200-96e2-11e9-9b31-4f70b67a0742.png)

**Comment by renefloor** [comment]
Should be fixed in 1.1.0
