### ISSUE TITLE
Class 'DefaultCacheManager' has no instance method 'getFileFromMemory'

### ISSUE THREAD

**Issue by zhancheng** [renefloor/flutter_cache_manager#98]
i guess the new version after this weekend has some problem .

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.7.8+hotfix.1, on Mac OS X 10.14.3 18D109,
    locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] Connected device (4 available)

**Comment by renefloor** [comment]
It has in the documentation (of version 1.1.0). (and I added that method).
https://pub.dev/documentation/flutter_cache_manager/latest/flutter_cache_manager/DefaultCacheManager-class.html

Can you try flutter pub upgrade?

**Comment by zhancheng** [comment]
@renefloor yes , i guess the problem is cache_network_image version does not match flutter_cache_manager, i delete the pre version and pub get again , it works. thanks.
